DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;


// Таблица пользователей
CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
COMMENT ON TABLE users IS 'Список пользователей';
COMMENT ON COLUMN users.name IS 'Имя пользователя';
COMMENT ON COLUMN users.email IS 'Email пользователя';


// Таблица предметов
CREATE TABLE IF NOT EXISTS items
(
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    owner_id    BIGINT REFERENCES USERS ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);
COMMENT ON TABLE items IS 'Список предметов';
COMMENT ON COLUMN items.name IS 'Название предмета';
COMMENT ON COLUMN items.description IS 'Описание предмета';
COMMENT ON COLUMN items.available IS 'Доступность для аренды';
COMMENT ON COLUMN items.owner_id IS 'Собственник вещи';
